from dotenv import load_dotenv
import os

# Загружаем переменные окружения из .env
load_dotenv()

TWITTER_USER_ID = os.getenv('TWITTER_USER_ID')
TWITTER_USERNAME = os.getenv('TWITTER_USERNAME')
TWITTER_CONSUMER_KEY= os.getenv('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET= os.getenv('TWITTER_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN= os.getenv('TWITTER_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET= os.getenv('TWITTER_ACCESS_TOKEN_SECRET')
TWITTER_BEARER_TOKEN = os.getenv('TWITTER_BEARER_TOKEN')
OPENAI_API_KEY= os.getenv('OPENAI_API_KEY')
ANTHROPIC_API_KEY= os.getenv('ANTHROPIC_API_KEY')
TELEGRAM_BOT_TOKEN= os.getenv('TELEGRAM_BOT_TOKEN')